/** @format */

export const PropertiesDummyData = [
	{
		id: 1,
		name: "adb",
		image: "/Assets/pexels-binyamin-mellish-106399.jpg",
		min_investment: "20 Lakhs",
		min_area: "100 sq.ft.",
		rental_yield: "9% - 16%",
		location: "Sector 23 ,Noida",
		city: "Noida",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 2,
		name: "adb",
		image: "/Assets/pexels-binyamin-mellish-186077.jpg",
		min_investment: "30 Lakhs",
		min_area: "150 sq.ft.",
		rental_yield: "5% - 12%",
		location: "Sector 23, New Delhi",
		city: "New Delhi",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 3,
		name: "adb",
		image: "/Assets/pexels-binyamin-mellish-1396132.jpg",
		min_investment: "40 Lakhs",
		min_area: "160 sq.ft.",
		rental_yield: "3% - 10%",
		location: "Sector 20 , NCR",
		city: "NCR",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 4,
		name: "adb",
		image: "/Assets/pexels-jessica-bryant-1370704.jpg",
		min_investment: "50 Lakhs",
		min_area: "200 sq.ft.",
		rental_yield: "6% - 13%",
		location: "Sector 21 ,New Delhi",
		city: "New Delhi",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 5,
		name: "adb",
		image: "/Assets/pexels-frans-van-heerden-1438834.jpg",
		min_investment: "20 Lakhs",
		min_area: "100 sq.ft.",
		rental_yield: "4% - 9%",
		location: "Sector 27 ,Noida",
		city: "Noida",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 6,
		name: "adb",
		image: "/Assets/pexels-pixabay-164522.jpg",
		min_investment: "10 Lakhs",
		min_area: "150 sq.ft.",
		rental_yield: "3% - 7%",
		location: "Sector 29 Noida",
		city: "Noida",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 7,
		name: "adb",
		image: "/Assets/pexels-pixabay-210617.jpg",
		min_investment: "50 Lakhs",
		min_area: "200 sq.ft.",
		rental_yield: "9% - 12%",
		location: "Sector 23 ,NCR",
		city: "NCR",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 8,
		name: "adb",
		image: "/Assets/pexels-pixabay-259588.jpg",
		min_investment: "20 Lakhs",
		min_area: "160 sq.ft.",
		rental_yield: "5% - 11%",
		location: "Sector 22 ,New Delhi",
		city: "New Delhi",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 9,
		name: "adb",
		image: "/Assets/pexels-pixabay-259646.jpg",
		min_investment: "15 Lakhs",
		min_area: "180 sq.ft.",
		rental_yield: "8% - 10%",
		location: "Sector 20 Noida",
		city: "Noida",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
	{
		id: 10,
		name: "adb",
		image: "/Assets/pexels-frans-van-heerden-1438834.jpg",
		min_investment: "60 Lakhs",
		min_area: "160 sq.ft.",
		rental_yield: "6% - 13%",
		location: "Sector 26 Noida",
		city: "Noida",
		contact: {
			email: "",
			mobile_number: "",
		},
	},
];
